### ISSUE TITLE
[Feature Request] AWS Lambda DD Forwarder Function Architectures Support

### ISSUE THREAD

**Issue by twmartin** [DataDog/datadog-serverless-functions#510]
It would be nice to have an out-of-the-box option to run the AWS Lambda Datadog Forwarder function on the new ARM-based Graviton2 architecture for improved performance and decreased cost.

https://aws.amazon.com/blogs/aws/aws-lambda-functions-powered-by-aws-graviton2-processor-run-your-functions-on-arm-and-get-up-to-34-better-price-performance/

**Comment by bryantbiggs** [comment]
for those who might be using Terraform, I just released support for this https://github.com/clowdhaus/terraform-aws-datadog-forwarders/pull/12

**Comment by cparmar** [comment]
@bryantbiggs The terraform was updated to support arm64 but does the forwarder definitely support arm64?

We tried to deploy the forwarder with the arm64 architecture but ran into errors with it:
![image](https://user-images.githubusercontent.com/1767111/192381815-9b6bbefa-69f2-448b-a1ee-652fcd8f601e.png)


We submitted a support ticket with Datadog but after some back and forth we were advised some of the forwarder's dependancies don't support arm64 and there wasn't any plans to support it in the near future (This was in July 2022).

Do you know if there are plans to support this - we could save over $10,000 a year by moving to arm64.

**Comment by julian-alarcon** [comment]
I will like to know if anybody tried in the last months the deployment on arm64, it will save a lot of costs!

**Comment by JesusPerez2TR** [comment]
> I will like to know if anybody tried in the last months the deployment on arm64, it will save a lot of costs!

I tried but it seems that it is not supported yet

**Comment by rblaine95** [comment]
Just FYI, tried today to run `arm64` with `3.105.0` of the Datadog Log Forwarder Lambda on Python `3.11` runtime.

Still not working.

_Edit to prevent noise:_ #740

**Comment by tyrcho** [comment]
This was finally implemented with https://github.com/DataDog/datadog-serverless-functions/pull/898 and released in https://github.com/DataDog/datadog-serverless-functions/releases/tag/aws-dd-forwarder-4.1.0
